/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsEnum,
  IsOptional,
  MaxLength,
  IsBoolean,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { EnumColumnDataType } from "./EnumColumnDataType";
import { Table } from "../../table/base/Table";
import { RecipeColumns } from "../../recipeColumns/base/RecipeColumns";

@ObjectType()
class Column {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    enum: EnumColumnDataType,
  })
  @IsEnum(EnumColumnDataType)
  @IsOptional()
  @Field(() => EnumColumnDataType, {
    nullable: true,
  })
  dataType?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name!: string | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isUnique!: boolean | null;

  @ApiProperty({
    required: false,
    type: Boolean,
  })
  @IsBoolean()
  @IsOptional()
  @Field(() => Boolean, {
    nullable: true,
  })
  isNullable!: boolean | null;

  @ApiProperty({
    required: false,
    type: () => Table,
  })
  @ValidateNested()
  @Type(() => Table)
  @IsOptional()
  table?: Table | null;

  @ApiProperty({
    required: false,
    type: () => [RecipeColumns],
  })
  @ValidateNested()
  @Type(() => RecipeColumns)
  @IsOptional()
  recipeColumnsItems?: Array<RecipeColumns>;
}

export { Column as Column };
