/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { ColumnListRelationFilter } from "../../column/base/ColumnListRelationFilter";
import { AnalysisResultListRelationFilter } from "../../analysisResult/base/AnalysisResultListRelationFilter";
import { RecipeExecutionListRelationFilter } from "../../recipeExecution/base/RecipeExecutionListRelationFilter";

@InputType()
class DataTableWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => ColumnListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ColumnListRelationFilter)
  @IsOptional()
  @Field(() => ColumnListRelationFilter, {
    nullable: true,
  })
  columns?: ColumnListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AnalysisResultListRelationFilter)
  @IsOptional()
  @Field(() => AnalysisResultListRelationFilter, {
    nullable: true,
  })
  analysisResults?: AnalysisResultListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => RecipeExecutionListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RecipeExecutionListRelationFilter)
  @IsOptional()
  @Field(() => RecipeExecutionListRelationFilter, {
    nullable: true,
  })
  recipeExecutions?: RecipeExecutionListRelationFilter;
}

export { DataTableWhereInput as DataTableWhereInput };
