/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { ObjectType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  IsDate,
  IsInt,
  Min,
  Max,
  IsOptional,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { IsJSONValue } from "../../validators";
import { GraphQLJSON } from "graphql-type-json";
import { JsonValue } from "type-fest";
import { QualityRule } from "../../qualityRule/base/QualityRule";
import { Recipe } from "../../recipe/base/Recipe";
import { RecipeColumns } from "../../recipeColumns/base/RecipeColumns";

@ObjectType()
class RecipeStep {
  @ApiProperty({
    required: true,
    type: String,
  })
  @IsString()
  @Field(() => String)
  id!: string;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  createdAt!: Date;

  @ApiProperty({
    required: true,
  })
  @IsDate()
  @Type(() => Date)
  @Field(() => Date)
  updatedAt!: Date;

  @ApiProperty({
    required: false,
    type: Number,
  })
  @IsInt()
  @Min(-999999999)
  @Max(999999999)
  @IsOptional()
  @Field(() => Number, {
    nullable: true,
  })
  order!: number | null;

  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  parameters!: JsonValue;

  @ApiProperty({
    required: false,
    type: () => QualityRule,
  })
  @ValidateNested()
  @Type(() => QualityRule)
  @IsOptional()
  qualityRule?: QualityRule | null;

  @ApiProperty({
    required: false,
    type: () => Recipe,
  })
  @ValidateNested()
  @Type(() => Recipe)
  @IsOptional()
  recipe?: Recipe | null;

  @ApiProperty({
    required: false,
    type: () => [RecipeColumns],
  })
  @ValidateNested()
  @Type(() => RecipeColumns)
  @IsOptional()
  recipeColumnsItems?: Array<RecipeColumns>;
}

export { RecipeStep as RecipeStep };
