/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { IntNullableFilter } from "../../util/IntNullableFilter";
import { JsonFilter } from "../../util/JsonFilter";
import { QualityRuleWhereUniqueInput } from "../../qualityRule/base/QualityRuleWhereUniqueInput";
import { RecipeWhereUniqueInput } from "../../recipe/base/RecipeWhereUniqueInput";
import { RecipeColumnsListRelationFilter } from "../../recipeColumns/base/RecipeColumnsListRelationFilter";

@InputType()
class RecipeStepWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: IntNullableFilter,
  })
  @Type(() => IntNullableFilter)
  @IsOptional()
  @Field(() => IntNullableFilter, {
    nullable: true,
  })
  order?: IntNullableFilter;

  @ApiProperty({
    required: false,
    type: JsonFilter,
  })
  @Type(() => JsonFilter)
  @IsOptional()
  @Field(() => JsonFilter, {
    nullable: true,
  })
  parameters?: JsonFilter;

  @ApiProperty({
    required: false,
    type: () => QualityRuleWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => QualityRuleWhereUniqueInput)
  @IsOptional()
  @Field(() => QualityRuleWhereUniqueInput, {
    nullable: true,
  })
  qualityRule?: QualityRuleWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RecipeWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => RecipeWhereUniqueInput)
  @IsOptional()
  @Field(() => RecipeWhereUniqueInput, {
    nullable: true,
  })
  recipe?: RecipeWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => RecipeColumnsListRelationFilter,
  })
  @ValidateNested()
  @Type(() => RecipeColumnsListRelationFilter)
  @IsOptional()
  @Field(() => RecipeColumnsListRelationFilter, {
    nullable: true,
  })
  recipeColumnsItems?: RecipeColumnsListRelationFilter;
}

export { RecipeStepWhereInput as RecipeStepWhereInput };
