/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { DatabaseService } from "../database.service";
import { DatabaseCreateInput } from "./DatabaseCreateInput";
import { Database } from "./Database";
import { DatabaseFindManyArgs } from "./DatabaseFindManyArgs";
import { DatabaseWhereUniqueInput } from "./DatabaseWhereUniqueInput";
import { DatabaseUpdateInput } from "./DatabaseUpdateInput";
import { TableFindManyArgs } from "../../table/base/TableFindManyArgs";
import { Table } from "../../table/base/Table";
import { TableWhereUniqueInput } from "../../table/base/TableWhereUniqueInput";

export class DatabaseControllerBase {
  constructor(protected readonly service: DatabaseService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Database })
  async createDatabase(
    @common.Body() data: DatabaseCreateInput
  ): Promise<Database> {
    return await this.service.createDatabase({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        connectionDetails: true,
        name: true,
        description: true,
        typeField: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Database] })
  @ApiNestedQuery(DatabaseFindManyArgs)
  async databases(@common.Req() request: Request): Promise<Database[]> {
    const args = plainToClass(DatabaseFindManyArgs, request.query);
    return this.service.databases({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        connectionDetails: true,
        name: true,
        description: true,
        typeField: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Database })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async database(
    @common.Param() params: DatabaseWhereUniqueInput
  ): Promise<Database | null> {
    const result = await this.service.database({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        connectionDetails: true,
        name: true,
        description: true,
        typeField: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Database })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateDatabase(
    @common.Param() params: DatabaseWhereUniqueInput,
    @common.Body() data: DatabaseUpdateInput
  ): Promise<Database | null> {
    try {
      return await this.service.updateDatabase({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          connectionDetails: true,
          name: true,
          description: true,
          typeField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Database })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteDatabase(
    @common.Param() params: DatabaseWhereUniqueInput
  ): Promise<Database | null> {
    try {
      return await this.service.deleteDatabase({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          connectionDetails: true,
          name: true,
          description: true,
          typeField: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/tables")
  @ApiNestedQuery(TableFindManyArgs)
  async findTables(
    @common.Req() request: Request,
    @common.Param() params: DatabaseWhereUniqueInput
  ): Promise<Table[]> {
    const query = plainToClass(TableFindManyArgs, request.query);
    const results = await this.service.findTables(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        creationDate: true,
        lastUpdate: true,
        owner: true,

        database: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/tables")
  async connectTables(
    @common.Param() params: DatabaseWhereUniqueInput,
    @common.Body() body: TableWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tables: {
        connect: body,
      },
    };
    await this.service.updateDatabase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/tables")
  async updateTables(
    @common.Param() params: DatabaseWhereUniqueInput,
    @common.Body() body: TableWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tables: {
        set: body,
      },
    };
    await this.service.updateDatabase({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/tables")
  async disconnectTables(
    @common.Param() params: DatabaseWhereUniqueInput,
    @common.Body() body: TableWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      tables: {
        disconnect: body,
      },
    };
    await this.service.updateDatabase({
      where: params,
      data,
      select: { id: true },
    });
  }
}
