/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { IsJSONValue } from "../../validators";
import {
  IsOptional,
  IsEnum,
  IsString,
  MaxLength,
  ValidateNested,
} from "class-validator";
import { GraphQLJSON } from "graphql-type-json";
import { InputJsonValue } from "../../types";
import { EnumRecipeTypeField } from "./EnumRecipeTypeField";
import { AnalysisResultCreateNestedManyWithoutRecipesInput } from "./AnalysisResultCreateNestedManyWithoutRecipesInput";
import { Type } from "class-transformer";
import { RecipeExecutionCreateNestedManyWithoutRecipesInput } from "./RecipeExecutionCreateNestedManyWithoutRecipesInput";

@InputType()
class RecipeCreateInput {
  @ApiProperty({
    required: false,
  })
  @IsJSONValue()
  @IsOptional()
  @Field(() => GraphQLJSON, {
    nullable: true,
  })
  steps?: InputJsonValue;

  @ApiProperty({
    required: false,
    enum: EnumRecipeTypeField,
  })
  @IsEnum(EnumRecipeTypeField)
  @IsOptional()
  @Field(() => EnumRecipeTypeField, {
    nullable: true,
  })
  typeField?: "Option1" | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultCreateNestedManyWithoutRecipesInput,
  })
  @ValidateNested()
  @Type(() => AnalysisResultCreateNestedManyWithoutRecipesInput)
  @IsOptional()
  @Field(() => AnalysisResultCreateNestedManyWithoutRecipesInput, {
    nullable: true,
  })
  analysisResults?: AnalysisResultCreateNestedManyWithoutRecipesInput;

  @ApiProperty({
    required: false,
    type: () => RecipeExecutionCreateNestedManyWithoutRecipesInput,
  })
  @ValidateNested()
  @Type(() => RecipeExecutionCreateNestedManyWithoutRecipesInput)
  @IsOptional()
  @Field(() => RecipeExecutionCreateNestedManyWithoutRecipesInput, {
    nullable: true,
  })
  recipeExecutions?: RecipeExecutionCreateNestedManyWithoutRecipesInput;
}

export { RecipeCreateInput as RecipeCreateInput };
