/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { RecipeService } from "../recipe.service";
import { RecipeCreateInput } from "./RecipeCreateInput";
import { Recipe } from "./Recipe";
import { RecipeFindManyArgs } from "./RecipeFindManyArgs";
import { RecipeWhereUniqueInput } from "./RecipeWhereUniqueInput";
import { RecipeUpdateInput } from "./RecipeUpdateInput";
import { AnalysisResultFindManyArgs } from "../../analysisResult/base/AnalysisResultFindManyArgs";
import { AnalysisResult } from "../../analysisResult/base/AnalysisResult";
import { AnalysisResultWhereUniqueInput } from "../../analysisResult/base/AnalysisResultWhereUniqueInput";
import { RecipeExecutionFindManyArgs } from "../../recipeExecution/base/RecipeExecutionFindManyArgs";
import { RecipeExecution } from "../../recipeExecution/base/RecipeExecution";
import { RecipeExecutionWhereUniqueInput } from "../../recipeExecution/base/RecipeExecutionWhereUniqueInput";

export class RecipeControllerBase {
  constructor(protected readonly service: RecipeService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Recipe })
  async createRecipe(@common.Body() data: RecipeCreateInput): Promise<Recipe> {
    return await this.service.createRecipe({
      data: data,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        steps: true,
        typeField: true,
        name: true,
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Recipe] })
  @ApiNestedQuery(RecipeFindManyArgs)
  async recipes(@common.Req() request: Request): Promise<Recipe[]> {
    const args = plainToClass(RecipeFindManyArgs, request.query);
    return this.service.recipes({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        steps: true,
        typeField: true,
        name: true,
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Recipe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async recipe(
    @common.Param() params: RecipeWhereUniqueInput
  ): Promise<Recipe | null> {
    const result = await this.service.recipe({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        steps: true,
        typeField: true,
        name: true,
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Recipe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateRecipe(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() data: RecipeUpdateInput
  ): Promise<Recipe | null> {
    try {
      return await this.service.updateRecipe({
        where: params,
        data: data,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          steps: true,
          typeField: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Recipe })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteRecipe(
    @common.Param() params: RecipeWhereUniqueInput
  ): Promise<Recipe | null> {
    try {
      return await this.service.deleteRecipe({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          steps: true,
          typeField: true,
          name: true,
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/analysisResults")
  @ApiNestedQuery(AnalysisResultFindManyArgs)
  async findAnalysisResults(
    @common.Req() request: Request,
    @common.Param() params: RecipeWhereUniqueInput
  ): Promise<AnalysisResult[]> {
    const query = plainToClass(AnalysisResultFindManyArgs, request.query);
    const results = await this.service.findAnalysisResults(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        results: true,

        recipe: {
          select: {
            id: true,
          },
        },

        dataTable: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/analysisResults")
  async connectAnalysisResults(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() body: AnalysisResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analysisResults: {
        connect: body,
      },
    };
    await this.service.updateRecipe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/analysisResults")
  async updateAnalysisResults(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() body: AnalysisResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analysisResults: {
        set: body,
      },
    };
    await this.service.updateRecipe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/analysisResults")
  async disconnectAnalysisResults(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() body: AnalysisResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analysisResults: {
        disconnect: body,
      },
    };
    await this.service.updateRecipe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/recipeExecutions")
  @ApiNestedQuery(RecipeExecutionFindManyArgs)
  async findRecipeExecutions(
    @common.Req() request: Request,
    @common.Param() params: RecipeWhereUniqueInput
  ): Promise<RecipeExecution[]> {
    const query = plainToClass(RecipeExecutionFindManyArgs, request.query);
    const results = await this.service.findRecipeExecutions(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        executedAt: true,
        results: true,
        isErrored: true,

        recipe: {
          select: {
            id: true,
          },
        },

        dataTable: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/recipeExecutions")
  async connectRecipeExecutions(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() body: RecipeExecutionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recipeExecutions: {
        connect: body,
      },
    };
    await this.service.updateRecipe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/recipeExecutions")
  async updateRecipeExecutions(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() body: RecipeExecutionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recipeExecutions: {
        set: body,
      },
    };
    await this.service.updateRecipe({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/recipeExecutions")
  async disconnectRecipeExecutions(
    @common.Param() params: RecipeWhereUniqueInput,
    @common.Body() body: RecipeExecutionWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      recipeExecutions: {
        disconnect: body,
      },
    };
    await this.service.updateRecipe({
      where: params,
      data,
      select: { id: true },
    });
  }
}
