/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import * as common from "@nestjs/common";
import * as swagger from "@nestjs/swagger";
import { isRecordNotFoundError } from "../../prisma.util";
import * as errors from "../../errors";
import { Request } from "express";
import { plainToClass } from "class-transformer";
import { ApiNestedQuery } from "../../decorators/api-nested-query.decorator";
import { TableService } from "../table.service";
import { TableCreateInput } from "./TableCreateInput";
import { Table } from "./Table";
import { TableFindManyArgs } from "./TableFindManyArgs";
import { TableWhereUniqueInput } from "./TableWhereUniqueInput";
import { TableUpdateInput } from "./TableUpdateInput";
import { ColumnFindManyArgs } from "../../column/base/ColumnFindManyArgs";
import { Column } from "../../column/base/Column";
import { ColumnWhereUniqueInput } from "../../column/base/ColumnWhereUniqueInput";
import { AnalysisResultFindManyArgs } from "../../analysisResult/base/AnalysisResultFindManyArgs";
import { AnalysisResult } from "../../analysisResult/base/AnalysisResult";
import { AnalysisResultWhereUniqueInput } from "../../analysisResult/base/AnalysisResultWhereUniqueInput";

export class TableControllerBase {
  constructor(protected readonly service: TableService) {}
  @common.Post()
  @swagger.ApiCreatedResponse({ type: Table })
  async createTable(@common.Body() data: TableCreateInput): Promise<Table> {
    return await this.service.createTable({
      data: {
        ...data,

        database: data.database
          ? {
              connect: data.database,
            }
          : undefined,
      },
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        creationDate: true,
        lastUpdate: true,
        owner: true,

        database: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get()
  @swagger.ApiOkResponse({ type: [Table] })
  @ApiNestedQuery(TableFindManyArgs)
  async tables(@common.Req() request: Request): Promise<Table[]> {
    const args = plainToClass(TableFindManyArgs, request.query);
    return this.service.tables({
      ...args,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        creationDate: true,
        lastUpdate: true,
        owner: true,

        database: {
          select: {
            id: true,
          },
        },
      },
    });
  }

  @common.Get("/:id")
  @swagger.ApiOkResponse({ type: Table })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async table(
    @common.Param() params: TableWhereUniqueInput
  ): Promise<Table | null> {
    const result = await this.service.table({
      where: params,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        name: true,
        description: true,
        creationDate: true,
        lastUpdate: true,
        owner: true,

        database: {
          select: {
            id: true,
          },
        },
      },
    });
    if (result === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return result;
  }

  @common.Patch("/:id")
  @swagger.ApiOkResponse({ type: Table })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async updateTable(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() data: TableUpdateInput
  ): Promise<Table | null> {
    try {
      return await this.service.updateTable({
        where: params,
        data: {
          ...data,

          database: data.database
            ? {
                connect: data.database,
              }
            : undefined,
        },
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
          creationDate: true,
          lastUpdate: true,
          owner: true,

          database: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Delete("/:id")
  @swagger.ApiOkResponse({ type: Table })
  @swagger.ApiNotFoundResponse({ type: errors.NotFoundException })
  async deleteTable(
    @common.Param() params: TableWhereUniqueInput
  ): Promise<Table | null> {
    try {
      return await this.service.deleteTable({
        where: params,
        select: {
          id: true,
          createdAt: true,
          updatedAt: true,
          name: true,
          description: true,
          creationDate: true,
          lastUpdate: true,
          owner: true,

          database: {
            select: {
              id: true,
            },
          },
        },
      });
    } catch (error) {
      if (isRecordNotFoundError(error)) {
        throw new errors.NotFoundException(
          `No resource was found for ${JSON.stringify(params)}`
        );
      }
      throw error;
    }
  }

  @common.Get("/:id/columns")
  @ApiNestedQuery(ColumnFindManyArgs)
  async findColumns(
    @common.Req() request: Request,
    @common.Param() params: TableWhereUniqueInput
  ): Promise<Column[]> {
    const query = plainToClass(ColumnFindManyArgs, request.query);
    const results = await this.service.findColumns(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        dataType: true,
        name: true,
        isUnique: true,
        isNullable: true,

        table: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/columns")
  async connectColumns(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        connect: body,
      },
    };
    await this.service.updateTable({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/columns")
  async updateColumns(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        set: body,
      },
    };
    await this.service.updateTable({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/columns")
  async disconnectColumns(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() body: ColumnWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      columns: {
        disconnect: body,
      },
    };
    await this.service.updateTable({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Get("/:id/analysisResults")
  @ApiNestedQuery(AnalysisResultFindManyArgs)
  async findAnalysisResults(
    @common.Req() request: Request,
    @common.Param() params: TableWhereUniqueInput
  ): Promise<AnalysisResult[]> {
    const query = plainToClass(AnalysisResultFindManyArgs, request.query);
    const results = await this.service.findAnalysisResults(params.id, {
      ...query,
      select: {
        id: true,
        createdAt: true,
        updatedAt: true,
        executionDate: true,
        resultData: true,
        issuesFound: true,
        appliedFilters: true,

        table: {
          select: {
            id: true,
          },
        },

        recipe: {
          select: {
            id: true,
          },
        },
      },
    });
    if (results === null) {
      throw new errors.NotFoundException(
        `No resource was found for ${JSON.stringify(params)}`
      );
    }
    return results;
  }

  @common.Post("/:id/analysisResults")
  async connectAnalysisResults(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() body: AnalysisResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analysisResults: {
        connect: body,
      },
    };
    await this.service.updateTable({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Patch("/:id/analysisResults")
  async updateAnalysisResults(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() body: AnalysisResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analysisResults: {
        set: body,
      },
    };
    await this.service.updateTable({
      where: params,
      data,
      select: { id: true },
    });
  }

  @common.Delete("/:id/analysisResults")
  async disconnectAnalysisResults(
    @common.Param() params: TableWhereUniqueInput,
    @common.Body() body: AnalysisResultWhereUniqueInput[]
  ): Promise<void> {
    const data = {
      analysisResults: {
        disconnect: body,
      },
    };
    await this.service.updateTable({
      where: params,
      data,
      select: { id: true },
    });
  }
}
