/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import { StringFilter } from "../../util/StringFilter";
import { Type } from "class-transformer";
import { IsOptional, ValidateNested } from "class-validator";
import { StringNullableFilter } from "../../util/StringNullableFilter";
import { DateTimeNullableFilter } from "../../util/DateTimeNullableFilter";
import { DatabaseWhereUniqueInput } from "../../database/base/DatabaseWhereUniqueInput";
import { ColumnListRelationFilter } from "../../column/base/ColumnListRelationFilter";
import { AnalysisResultListRelationFilter } from "../../analysisResult/base/AnalysisResultListRelationFilter";

@InputType()
class TableWhereInput {
  @ApiProperty({
    required: false,
    type: StringFilter,
  })
  @Type(() => StringFilter)
  @IsOptional()
  @Field(() => StringFilter, {
    nullable: true,
  })
  id?: StringFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  name?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  description?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  creationDate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: DateTimeNullableFilter,
  })
  @Type(() => DateTimeNullableFilter)
  @IsOptional()
  @Field(() => DateTimeNullableFilter, {
    nullable: true,
  })
  lastUpdate?: DateTimeNullableFilter;

  @ApiProperty({
    required: false,
    type: StringNullableFilter,
  })
  @Type(() => StringNullableFilter)
  @IsOptional()
  @Field(() => StringNullableFilter, {
    nullable: true,
  })
  owner?: StringNullableFilter;

  @ApiProperty({
    required: false,
    type: () => DatabaseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DatabaseWhereUniqueInput)
  @IsOptional()
  @Field(() => DatabaseWhereUniqueInput, {
    nullable: true,
  })
  database?: DatabaseWhereUniqueInput;

  @ApiProperty({
    required: false,
    type: () => ColumnListRelationFilter,
  })
  @ValidateNested()
  @Type(() => ColumnListRelationFilter)
  @IsOptional()
  @Field(() => ColumnListRelationFilter, {
    nullable: true,
  })
  columns?: ColumnListRelationFilter;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultListRelationFilter,
  })
  @ValidateNested()
  @Type(() => AnalysisResultListRelationFilter)
  @IsOptional()
  @Field(() => AnalysisResultListRelationFilter, {
    nullable: true,
  })
  analysisResults?: AnalysisResultListRelationFilter;
}

export { TableWhereInput as TableWhereInput };
