/*
------------------------------------------------------------------------------ 
This code was generated by Amplication. 
 
Changes to this file will be lost if the code is regenerated. 

There are other ways to to customize your code, see this doc to learn more
https://docs.amplication.com/how-to/custom-code

------------------------------------------------------------------------------
  */
import { InputType, Field } from "@nestjs/graphql";
import { ApiProperty } from "@nestjs/swagger";
import {
  IsString,
  MaxLength,
  IsOptional,
  IsDate,
  ValidateNested,
} from "class-validator";
import { Type } from "class-transformer";
import { DatabaseWhereUniqueInput } from "../../database/base/DatabaseWhereUniqueInput";
import { ColumnCreateNestedManyWithoutTablesInput } from "./ColumnCreateNestedManyWithoutTablesInput";
import { AnalysisResultCreateNestedManyWithoutTablesInput } from "./AnalysisResultCreateNestedManyWithoutTablesInput";

@InputType()
class TableCreateInput {
  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  name?: string | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  description?: string | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  creationDate?: Date | null;

  @ApiProperty({
    required: false,
  })
  @IsDate()
  @Type(() => Date)
  @IsOptional()
  @Field(() => Date, {
    nullable: true,
  })
  lastUpdate?: Date | null;

  @ApiProperty({
    required: false,
    type: String,
  })
  @IsString()
  @MaxLength(1000)
  @IsOptional()
  @Field(() => String, {
    nullable: true,
  })
  owner?: string | null;

  @ApiProperty({
    required: false,
    type: () => DatabaseWhereUniqueInput,
  })
  @ValidateNested()
  @Type(() => DatabaseWhereUniqueInput)
  @IsOptional()
  @Field(() => DatabaseWhereUniqueInput, {
    nullable: true,
  })
  database?: DatabaseWhereUniqueInput | null;

  @ApiProperty({
    required: false,
    type: () => ColumnCreateNestedManyWithoutTablesInput,
  })
  @ValidateNested()
  @Type(() => ColumnCreateNestedManyWithoutTablesInput)
  @IsOptional()
  @Field(() => ColumnCreateNestedManyWithoutTablesInput, {
    nullable: true,
  })
  columns?: ColumnCreateNestedManyWithoutTablesInput;

  @ApiProperty({
    required: false,
    type: () => AnalysisResultCreateNestedManyWithoutTablesInput,
  })
  @ValidateNested()
  @Type(() => AnalysisResultCreateNestedManyWithoutTablesInput)
  @IsOptional()
  @Field(() => AnalysisResultCreateNestedManyWithoutTablesInput, {
    nullable: true,
  })
  analysisResults?: AnalysisResultCreateNestedManyWithoutTablesInput;
}

export { TableCreateInput as TableCreateInput };
